export type Option = { label: string; value: string }

export const GENDER_OPTIONS: Option[] = [
  { label: 'Male', value: 'Male' },
  { label: 'Female', value: 'Female' },
  { label: 'Non-binary', value: 'Non-binary' },
  { label: 'Prefer not to say', value: 'Prefer not to say' },
]

export const CATEGORY_OPTIONS: Option[] = [
  { label: 'Lifestyle', value: 'Lifestyle' },
  { label: 'Fashion', value: 'Fashion' },
  { label: 'Beauty', value: 'Beauty' },
  { label: 'Fitness', value: 'Fitness' },
  { label: 'Food', value: 'Food' },
  { label: 'Travel', value: 'Travel' },
  { label: 'Tech', value: 'Tech' },
  { label: 'Gaming', value: 'Gaming' },
  { label: 'Education', value: 'Education' },
  { label: 'Business', value: 'Business' },
  { label: 'Finance', value: 'Finance' },
  { label: 'Entertainment', value: 'Entertainment' },
  { label: 'Sports', value: 'Sports' },
  { label: 'Automotive', value: 'Automotive' },
  { label: 'Home & Living', value: 'Home & Living' },
]

export const SWEDISH_COUNTIES = [
  'Blekinge län',
  'Dalarnas län',
  'Gotlands län',
  'Gävleborgs län',
  'Hallands län',
  'Jämtlands län',
  'Jönköpings län',
  'Kalmar län',
  'Kronobergs län',
  'Norrbottens län',
  'Skåne län',
  'Stockholms län',
  'Södermanlands län',
  'Uppsala län',
  'Värmlands län',
  'Västerbottens län',
  'Västernorrlands län',
  'Västmanlands län',
  'Västra Götalands län',
  'Örebro län',
  'Östergötlands län',
] as const

export const SWEDISH_MUNICIPALITIES: Record<string, string[]> = {
  'Blekinge län': ['Karlskrona', 'Ronneby', 'Karlshamn', 'Sölvesborg', 'Olofström'],
  'Dalarnas län': ['Falun', 'Borlänge', 'Mora', 'Ludvika', 'Avesta'],
  'Gotlands län': ['Visby', 'Slite', 'Hemse', 'Klintehamn'],
  'Gävleborgs län': ['Gävle', 'Sandviken', 'Hudiksvall', 'Bollnäs', 'Söderhamn'],
  'Hallands län': ['Halmstad', 'Varberg', 'Kungsbacka', 'Falkenberg', 'Laholm'],
  'Jämtlands län': ['Östersund', 'Åre', 'Strömsund', 'Krokom', 'Bräcke'],
  'Jönköpings län': ['Jönköping', 'Nässjö', 'Värnamo', 'Vetlanda', 'Eksjö'],
  'Kalmar län': ['Kalmar', 'Västervik', 'Oskarshamn', 'Nybro', 'Vimmerby'],
  'Kronobergs län': ['Växjö', 'Ljungby', 'Älmhult', 'Alvesta', 'Tingsryd'],
  'Norrbottens län': ['Luleå', 'Piteå', 'Boden', 'Kiruna', 'Gällivare'],
  'Skåne län': ['Malmö', 'Helsingborg', 'Lund', 'Kristianstad', 'Ystad'],
  'Stockholms län': ['Stockholm', 'Solna', 'Danderyd', 'Lidingö', 'Täby', 'Nacka', 'Södertälje', 'Haninge'],
  'Södermanlands län': ['Eskilstuna', 'Nyköping', 'Katrineholm', 'Strängnäs', 'Flen'],
  'Uppsala län': ['Uppsala', 'Enköping', 'Östhammar', 'Knivsta', 'Tierp'],
  'Värmlands län': ['Karlstad', 'Arvika', 'Kristinehamn', 'Sunne', 'Säffle'],
  'Västerbottens län': ['Umeå', 'Skellefteå', 'Lycksele', 'Vilhelmina', 'Nordmaling'],
  'Västernorrlands län': ['Sundsvall', 'Örnsköldsvik', 'Härnösand', 'Timrå', 'Kramfors'],
  'Västmanlands län': ['Västerås', 'Köping', 'Sala', 'Hallstahammar', 'Fagersta'],
  'Västra Götalands län': ['Göteborg', 'Borås', 'Trollhättan', 'Skövde', 'Uddevalla'],
  'Örebro län': ['Örebro', 'Karlskoga', 'Lindesberg', 'Kumla', 'Hallsberg'],
  'Östergötlands län': ['Linköping', 'Norrköping', 'Motala', 'Mjölby', 'Finspång'],
}

type CountryOption = { code: string; label: string; flag: string }

function toFlagEmoji(code: string) {
  return code
    .toUpperCase()
    .replace(/./g, (char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
}

// Complete ISO 3166-1 country list (English short names, sourced from ICU/CLDR).
// This is the single source of truth so the picker is identical on EVERY JS
// engine: React Native's Hermes lacks Intl.supportedValuesOf (and often a usable
// Intl.DisplayNames), so we must not depend on them for the base list — doing so
// previously collapsed the picker to ~55 countries on-device. Intl.DisplayNames,
// when present, is used only to localize the label text on top of this map.
const COUNTRY_NAMES: Record<string, string> = {
  AF: "Afghanistan",
  AX: "Åland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AG: "Antigua & Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia & Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  VG: "British Virgin Islands",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  BQ: "Caribbean Netherlands",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo - Brazzaville",
  CD: "Congo - Kinshasa",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Côte d’Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czechia",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HK: "Hong Kong SAR China",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao SAR China",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar (Burma)",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  KP: "North Korea",
  MK: "North Macedonia",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territories",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn Islands",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  WS: "Samoa",
  SM: "San Marino",
  ST: "São Tomé & Príncipe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SX: "Sint Maarten",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  KR: "South Korea",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  BL: "St. Barthélemy",
  SH: "St. Helena",
  KN: "St. Kitts & Nevis",
  LC: "St. Lucia",
  MF: "St. Martin",
  PM: "St. Pierre & Miquelon",
  VC: "St. Vincent & Grenadines",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard & Jan Mayen",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad & Tobago",
  TN: "Tunisia",
  TR: "Türkiye",
  TM: "Turkmenistan",
  TC: "Turks & Caicos Islands",
  TV: "Tuvalu",
  VI: "U.S. Virgin Islands",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VA: "Vatican City",
  VE: "Venezuela",
  VN: "Vietnam",
  WF: "Wallis & Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
}

export function getCountryOptions(): CountryOption[] {
  const DisplayNamesCtor = (globalThis.Intl as { DisplayNames?: new (locales: string[], options: { type: 'region' }) => { of: (code: string) => string | undefined } } | undefined)
    ?.DisplayNames
  let displayNames: { of: (code: string) => string | undefined } | null = null
  try {
    displayNames = DisplayNamesCtor ? new DisplayNamesCtor(['en'], { type: 'region' }) : null
  } catch {
    displayNames = null
  }

  const all = Object.keys(COUNTRY_NAMES).map((code) => {
    let label = COUNTRY_NAMES[code]
    if (displayNames) {
      try {
        const localized = displayNames.of(code)
        if (localized && localized !== code) label = localized
      } catch {
        // keep the static CLDR label
      }
    }
    return { code, label, flag: toFlagEmoji(code) }
  })

  const sweden = all.find((item) => item.code === 'SE')
  const rest = all.filter((item) => item.code !== 'SE').sort((a, b) => a.label.localeCompare(b.label))
  return sweden ? [sweden, ...rest] : rest
}

function normalizeCountryValue(value: string) {
  return value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-zA-Z]/g, '')
    .toLowerCase()
}

export function findCountryByValue(value?: string | null): CountryOption | null {
  const trimmed = value?.trim()
  if (!trimmed) return null

  const normalized = normalizeCountryValue(trimmed)
  const directCode = getCountryOptions().find((item) => item.code.toLowerCase() === trimmed.toLowerCase())
  if (directCode) return directCode

  const directLabel = getCountryOptions().find((item) => normalizeCountryValue(item.label) === normalized)
  if (directLabel) return directLabel

  return null
}

export const PHONE_CODE_OPTIONS: Option[] = [
  { label: '🇸🇪 (+46)', value: '+46' },
  { label: '🇳🇴 (+47)', value: '+47' },
  { label: '🇩🇰 (+45)', value: '+45' },
  { label: '🇫🇮 (+358)', value: '+358' },
  { label: '🇮🇸 (+354)', value: '+354' },
  { label: '🇬🇧 (+44)', value: '+44' },
  { label: '🇮🇪 (+353)', value: '+353' },
  { label: '🇩🇪 (+49)', value: '+49' },
  { label: '🇫🇷 (+33)', value: '+33' },
  { label: '🇪🇸 (+34)', value: '+34' },
  { label: '🇮🇹 (+39)', value: '+39' },
  { label: '🇳🇱 (+31)', value: '+31' },
  { label: '🇧🇪 (+32)', value: '+32' },
  { label: '🇵🇹 (+351)', value: '+351' },
  { label: '🇨🇭 (+41)', value: '+41' },
  { label: '🇦🇹 (+43)', value: '+43' },
  { label: '🇵🇱 (+48)', value: '+48' },
  { label: '🇨🇿 (+420)', value: '+420' },
  { label: '🇸🇰 (+421)', value: '+421' },
  { label: '🇭🇺 (+36)', value: '+36' },
  { label: '🇷🇴 (+40)', value: '+40' },
  { label: '🇭🇷 (+385)', value: '+385' },
  { label: '🇸🇮 (+386)', value: '+386' },
  // US and Canada share the +1 dial code; combine into one entry so selection
  // and the displayed flag don't collapse to whichever appears first.
  { label: '🇺🇸🇨🇦 (+1)', value: '+1' },
  { label: '🇲🇽 (+52)', value: '+52' },
  { label: '🇧🇷 (+55)', value: '+55' },
  { label: '🇦🇷 (+54)', value: '+54' },
  { label: '🇦🇺 (+61)', value: '+61' },
  { label: '🇳🇿 (+64)', value: '+64' },
  { label: '🇯🇵 (+81)', value: '+81' },
  { label: '🇰🇷 (+82)', value: '+82' },
  { label: '🇨🇳 (+86)', value: '+86' },
  { label: '🇮🇳 (+91)', value: '+91' },
  { label: '🇸🇬 (+65)', value: '+65' },
  { label: '🇹🇭 (+66)', value: '+66' },
  { label: '🇲🇾 (+60)', value: '+60' },
  { label: '🇮🇩 (+62)', value: '+62' },
  { label: '🇵🇭 (+63)', value: '+63' },
  { label: '🇻🇳 (+84)', value: '+84' },
  { label: '🇦🇪 (+971)', value: '+971' },
  { label: '🇸🇦 (+966)', value: '+966' },
  { label: '🇹🇷 (+90)', value: '+90' },
  { label: '🇮🇱 (+972)', value: '+972' },
  { label: '🇿🇦 (+27)', value: '+27' },
]

export function formatCountyLabel(value?: string | null) {
  if (!value) return ''
  return value.replace(/ län$/i, ' County')
}

export const COUNTRY_TO_PHONE_CODE: Record<string, string> = {
  SE: '+46',
  NO: '+47',
  DK: '+45',
  FI: '+358',
  IS: '+354',
  GB: '+44',
  IE: '+353',
  DE: '+49',
  FR: '+33',
  ES: '+34',
  IT: '+39',
  NL: '+31',
  BE: '+32',
  PT: '+351',
  CH: '+41',
  AT: '+43',
  PL: '+48',
  CZ: '+420',
  SK: '+421',
  HU: '+36',
  RO: '+40',
  HR: '+385',
  SI: '+386',
  US: '+1',
  CA: '+1',
  MX: '+52',
  BR: '+55',
  AR: '+54',
  AU: '+61',
  NZ: '+64',
  JP: '+81',
  KR: '+82',
  CN: '+86',
  IN: '+91',
  SG: '+65',
  TH: '+66',
  MY: '+60',
  ID: '+62',
  PH: '+63',
  VN: '+84',
  AE: '+971',
  SA: '+966',
  TR: '+90',
  IL: '+972',
  ZA: '+27',
}
